"""enforced lengths on strings

Revision ID: 43a5266090b0
Revises: 8cbc07ba6273
Create Date: 2025-08-16 09:08:36.939070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a5266090b0'
down_revision: Union[str, Sequence[str], None] = '8cbc07ba6273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               nullable=False)
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('clients_phone_key'), 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('clients_phone_key'), 'clients', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
