"""add alerts and blocks

Revision ID: 4aecb40ab146
Revises: c1a2b3d4e5f6
Create Date: 2025-09-13 00:39:53.841239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aecb40ab146'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Enum('SENDER', 'RECIPIENT', name='block_type_enum'), nullable=False),
    sa.Column('subject_account_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_type', 'subject_account_id', name='uq_blocks_type_subject')
    )
    op.create_index(op.f('ix_blocks_subject_account_id'), 'blocks', ['subject_account_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('recipient_account_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_recipient_account_id'), 'alerts', ['recipient_account_id'], unique=False)
    op.create_index('ix_alerts_recipient_created', 'alerts', ['recipient_account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_sender_account_id'), 'alerts', ['sender_account_id'], unique=False)
    op.create_index('ix_alerts_sender_created', 'alerts', ['sender_account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_transaction_id'), 'alerts', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_transaction_id'), table_name='alerts')
    op.drop_index('ix_alerts_sender_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_sender_account_id'), table_name='alerts')
    op.drop_index('ix_alerts_recipient_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_recipient_account_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_blocks_subject_account_id'), table_name='blocks')
    op.drop_table('blocks')
    op.execute("DROP TYPE IF EXISTS block_type_enum")
    # ### end Alembic commands ###
