"""made global transaction model

Revision ID: 59ba1d5fcdfe
Revises: 2d0db0b9ee9d
Create Date: 2025-09-07 11:28:35.554325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ba1d5fcdfe'
down_revision: Union[str, Sequence[str], None] = '2d0db0b9ee9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
