"""create beneficiaries table fixed

Revision ID: 7c26f8cfb90d
Revises: 140a70c24577
Create Date: 2025-10-12 12:12:57.572735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c26f8cfb90d'
down_revision: Union[str, Sequence[str], None] = '140a70c24577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'recipient_user_id', name='uq_beneficiaries_owner_recipient')
    )
    op.create_index(op.f('ix_beneficiaries_owner_user_id'), 'beneficiaries', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_recipient_user_id'), 'beneficiaries', ['recipient_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beneficiaries_recipient_user_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_owner_user_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
