"""autogen models

Revision ID: 9d70210d2bd2
Revises: 2d0db0b9ee9d
Create Date: 2025-09-07 12:16:08.109217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d70210d2bd2'
down_revision: Union[str, Sequence[str], None] = '2d0db0b9ee9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number', name='uq_accounts_account_number')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='ZAR', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('kind', sa.String(length=30), server_default='transfer', nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_recipient_created', 'transactions', ['recipient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_id'), 'transactions', ['recipient_id'], unique=False)
    op.create_index('ix_transactions_sender_created', 'transactions', ['sender_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_sender_id'), 'transactions', ['sender_id'], unique=False)
    #SHOULD DROP CLIENTS TABLE AS SOON AS NEW MODELS ARE READY AND WORKING! NB
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_pkey')),
    sa.UniqueConstraint('email', name=op.f('uq_clients_email'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone', name=op.f('uq_clients_phone'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_transactions_sender_id'), table_name='transactions')
    op.drop_index('ix_transactions_sender_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_id'), table_name='transactions')
    op.drop_index('ix_transactions_recipient_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
