"""move payment_history from transactions to accounts (schema) and added admin field

Revision ID: c2be8ba643f6
Revises: 4fcf954093b1
Create Date: 2025-09-23 19:21:27.310403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2be8ba643f6'
down_revision: Union[str, Sequence[str], None] = '4fcf954093b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('payment_history', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('transactions', 'payment_history')
    op.add_column('users', sa.Column('admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    op.add_column('transactions', sa.Column('payment_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'payment_history')
    # ### end Alembic commands ###
